### ISSUE TITLE
NullReferenceException when loop to play a video list

### ISSUE THREAD

**Issue by biduan** [unosquare/ffmediaelement#117]
more than two video to repeat play. issue would happen.
Below are the reproduce steps:
on the MediaElement.MediaEnded event.
1. Video 1 play complete ,then update MediaElement source to Video2
2.Video 2 play complete ,then update MediaElement source back to Video1
3. Repeat step 1

exception throw if play multiple times 

发生了 System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.get_Id()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Unosquare.FFME.Commands.MediaCommand.<ExecuteAsync>d__14.MoveNext() in C:\Reception\3rd\ffmediaelement-2.0.0-b1\Unosquare.FFME\Commands\MediaCommand.cs:line 69
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Unosquare.FFME.Commands.MediaCommand.ExecuteAsync()
   at Unosquare.FFME.Commands.MediaCommandManager.<>c__DisplayClass12_0.<<Open>b__0>d.MoveNext() in C:\Reception\3rd\ffmediaelement-2.0.0-b1\Unosquare.FFME\Commands\MediaCommandManager.cs:line 77
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Unosquare.FFME.Commands.MediaCommandManager.<Open>d__12.MoveNext() in C:\Reception\3rd\ffmediaelement-2.0.0-b1\Unosquare.FFME\Commands\MediaCommandManager.cs:line 74
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Unosquare.FFME.MediaElement.<OnSourcePropertyChanged>d__80.MoveNext() in C:\Reception\3rd\ffmediaelement-2.0.0-b1\Unosquare.FFME\MediaElement.DependencyProperties.cs:line 54

**Comment by mariodivece** [comment]
Could you try with the latest nuget? https://www.nuget.org/packages/FFME.Windows

**Comment by mariodivece** [comment]
Any updates here? Could you try again?

**Comment by mariodivece** [comment]
Please try again with the Beta 7 NuGet package. Reopen if you run into this issue again.
