### ISSUE TITLE
InvalidOperationException: "Nullable object must have a value." on MediaElement.NaturalDuration

### ISSUE THREAD

**Issue by CyberSinh** [unosquare/ffmediaelement#209]
## Issue Categories

 - Bug

## Version Information

 - NuGet Package *3.4.230*

## Issue Description

```
System.InvalidOperationException: "Nullable object must have a value."
  -->  System.Reflection.TargetInvocationException: "Exception has been thrown by the target of an invocation."

-> System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
-> Unosquare.FFME.MediaElement.get_NaturalDuration()
--- End of inner System.InvalidOperationException stack trace ---
-> System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
-> System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
-> System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
-> System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
-> System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
-> Unosquare.FFME.Platform.PropertyMapper.SnapshotNotifications(MediaElement m, Dictionary`2 target)
-> Unosquare.FFME.Platform.PropertyMapper.DetectNotificationPropertyChanges(MediaElement m, Dictionary`2 lastSnapshot)
-> Unosquare.FFME.MediaElement.<StartPropertyUpdatesWorker>b__6_0()
-> Unosquare.FFME.Platform.GuiTimer.RunTimerCycle(Object state)
-> Unosquare.FFME.Platform.GuiTimer.<CreateDispatcherTimer>b__23_0(Object s, EventArgs e)
-> System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
-> System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
-> System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
This exception shouldn't happen because MediaElement.NaturalDuration already check for non null value before using the `TimeSpan?` : `MediaCore?.State.NaturalDuration == null`

Perhaps it could be a sync threading issue. Is it possible that a background thread set the `MediaEngine.Container`  to `null` while the `MediaElement.NaturalDuration` property is read in the main thread?

Thanks.

**Comment by jnschulze** [comment]
Same here. My test app that had been running for days just crashed this morning.
```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at Unosquare.FFME.MediaElement.get_NaturalDuration() in ffmediaelement\Unosquare.FFME.Windows\MediaElement.MediaProperties.cs:line 19.
   --- End of inner System.InvalidOperationException stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Unosquare.FFME.Platform.PropertyMapper.SnapshotNotifications(MediaElement m, Dictionary`2 target) in ffmediaelement\Unosquare.FFME.Windows\Platform\PropertyMapper.cs:line 139.
   at Unosquare.FFME.Platform.PropertyMapper.DetectNotificationPropertyChanges(MediaElement m, Dictionary`2 lastSnapshot) in ffmediaelement\Unosquare.FFME.Windows\Platform\PropertyMapper.cs:line 84.
   at Unosquare.FFME.MediaElement.UpdateNotificationProperties() in ffmediaelement\Unosquare.FFME.Windows\MediaElement.PropertyUpdates.cs:line 103.
   at Unosquare.FFME.MediaElement.<StartPropertyUpdatesWorker>b__6_0() in ffmediaelement\Unosquare.FFME.Windows\MediaElement.PropertyUpdates.cs:line 71.
   at Unosquare.FFME.Platform.GuiTimer.RunTimerCycle(Object state) in ffmediaelement\Unosquare.FFME.Windows\Platform\GuiTimer.cs:line 169.
   at Unosquare.FFME.Platform.GuiTimer.<CreateDispatcherTimer>b__23_0(Object s, EventArgs e) in ffmediaelement\Unosquare.FFME.Windows\Platform\GuiTimer.cs:line 205.
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at ...
```
