### ISSUE TITLE
Unable to play 4k video

### ISSUE THREAD

**Issue by masiton** [unosquare/ffmediaelement#24]
Attempt to play HEV x265 4k file results in error. Tried both 64 and 32 bit builds, makes no difference. Box is Windows 10 Pro 64bit.

Source video file: http://4ksamples.com/elysium-2013-2160p-1-minute-sample-footage/
Exception detail:

An unhandled exception of type 'System.AccessViolationException' occurred in Unosquare.FFmpegMediaElement.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Stacktrace:

   at FFmpeg.AutoGen.ffmpeg.swr_convert(SwrContext* s, SByte** out, Int32 out_count, SByte** in, Int32 in_count)
   at Unosquare.FFmpegMediaElement.FFmpegMedia.CreateMediaFrameFromDecodedWaveHolder() in Unosquare.FFmpegMediaElement\FFmpegMedia.Decoding.cs:line 315
   at Unosquare.FFmpegMediaElement.FFmpegMedia.PullMediaFrame() in ffmediaelement\Unosquare.FFmpegMediaElement\FFmpegMedia.Decoding.cs:line 515
   at Unosquare.FFmpegMediaElement.FFmpegMedia.InternalFillFramesCache(TimeSpan timeout) in ffmediaelement\Unosquare.FFmpegMediaElement\FFmpegMedia.cs:line 205
   at Unosquare.FFmpegMediaElement.FFmpegMedia.InternalLoadFrames(Decimal renderTime) in ffmediaelement\Unosquare.FFmpegMediaElement\FFmpegMedia.cs:line 434
   at Unosquare.FFmpegMediaElement.FFmpegMedia.ExtractMediaFramesContinuously() in ffmediaelement\Unosquare.FFmpegMediaElement\FFmpegMedia.cs:line 581
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

An unhandled exception of type 'System.AccessViolationException' occurred in Unosquare.FFmpegMediaElement.dll

Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

**Comment by mariodivece** [comment]
I believe H.265 support in FFmpeg is still experimental... 
See the note here: https://trac.ffmpeg.org/wiki/Encode/H.265

**Comment by mariodivece** [comment]
I am rewriting the decoder from scratch and this 4k video sample stutters and brings the CPU up to an almost constant 100% on a 4-year old laptop (i5). I tried the built-in media player in Windows and I see the exact same behavior. I will try with a more powerful machine in a few more days and let you know the results. I think I may need to scale down the image before rendering it because each frame is just too big! Good experiment and good sample. Thanks.

**Comment by masiton** [comment]
It's because HW acceleration isn't all that good in current LTS version of VLC. If you go to their website and get the nightly build, your playback will be smooth with CPU capping 50 percent tops.

OM

On 25 May 2017, at 01:35, Mario Di Vece <notifications@github.com<mailto:notifications@github.com>> wrote:


I am rewriting the decoder from scratch and this 4k video sample stutters and brings the CPU up to an almost constant 100% on a 4-year old laptop (i5). I tried the built-in media player in Windows and I see the exact same behavior. I will try with a more powerful machine in a few more days and let you know the results. I think I may need to scale down the image before rendering it because each frame is just too big! Good experiment and good sample. Thanks.

**Comment by mariodivece** [comment]
It renders fine with the new control but the CPU usage is high on a 6800k!
I can't fix HW acceleration in FFmpeg binaries so I am just going to close this issue.
![image](https://user-images.githubusercontent.com/351978/27097092-be26e96a-5038-11e7-9a34-c09cd095be1d.png)
