### ISSUE TITLE
Crash when Open video file

### ISSUE THREAD

**Issue by mortalV** [unosquare/ffmediaelement#264]
*Sometimes opening of video file generate exception*

## Issue Categories

 - [x ] Bug
 - [x ] Not sure

## Version Information

 - [ x] NuGet Package *4.0.260*

## Steps to Reproduce

1. hide MediaElement
2. open video file
3. play it
4. when state changed to plaing show MediaElement
5. after media ended close it
6. go to 1

## Expected Results

 - Playing videos without crash
 
### XAML
```xml
<MainWindow>
<Canvas x:Name="LayoutRoot" >
        <ffme:MediaElement x:Name="PlayerFF" Background="Transparent" LoadedBehavior="Manual" UnloadedBehavior="Manual" ScrubbingEnabled="False"  />
    </Canvas>
</MainWindow>
```

### C#
```csharp

private void PlayerFF_MediaStateChanged(object sender, Unosquare.FFME.Events.MediaStateChangedRoutedEventArgs e)
        {
            e.Handled = true;
            if (e.MediaState == MediaState.Play)
            {
                PlayerFF.Visibility = Visibility.Visible;
            }
        }

...

PlayerFF.Visibility = Visibility.Hidden;
await PlayerFF.Stop();
await PlayerFF.Close();
await PlayerFF.Open(new Uri(currBanner.item.Video));


sometimes, often but not always and not at all devices generated exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Unosquare.FFME.Primitives.MediaBlockBuffer.IndexOf(TimeSpan renderTime)
   at Unosquare.FFME.Primitives.MediaBlockBuffer.get_Item(TimeSpan at)
   at Unosquare.FFME.MediaEngine.<>c__DisplayClass154_0.<StartBlockRenderingWorker>b__0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by mariodivece** [comment]
Did you also try with the current master codebase? This should have been fixed by now. Could you test and let me know the results please?

**Comment by mortalV** [comment]
I'll try and describe result.

**Comment by mortalV** [comment]
I've build last master and have another exception

```C#
System.Threading.SynchronizationLockException: The lock is being disposed while still being used. It either is being held by a thread and/or has active waiters waiting to acquire the lock.
   at System.Threading.ReaderWriterLockSlim.Dispose(Boolean disposing)
   at Unosquare.FFME.Primitives.SyncLockerFactory.SyncLockerSlim.Dispose(Boolean alsoManaged)
   at Unosquare.FFME.Primitives.SyncLockerFactory.SyncLockerSlim.Dispose()
   at Unosquare.FFME.Primitives.MediaBlockBuffer.Dispose()
   at Unosquare.FFME.Commands.DirectCloseCommand.PerformActions()
   at Unosquare.FFME.Primitives.PromiseBase.Execute()
   at Unosquare.FFME.Primitives.PromiseBase.<BeginExecute>b__16_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
`

**Comment by mariodivece** [comment]
Could you test again with the latest codebase? This exception should not be thrown now. Thanks for reporting the issue. If the problem persists, please let me know and I'll reopen.
