### ISSUE TITLE
Latest build randomly crashes host process

### ISSUE THREAD

**Issue by olegsavelos** [unosquare/ffmediaelement#370]
I have tried the latest build 4.1.29 with FFMpeg 4.1.1 and the hosting process started to crash.

Here is stack trace

```
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Unosquare.FFME.Container.MediaContainer.get_MediaStreamSize()
   at Unosquare.FFME.Engine.MediaEngineState.UpdateFixedContainerProperties()
   at Unosquare.FFME.Commands.CommandManager.PostProcessDirectCommand(DirectCommandType, System.Exception, Boolean)
   at Unosquare.FFME.Commands.CommandManager+<>c__DisplayClass43_0.<ExecuteDirectCommand>b__0()
   at System.Threading.Tasks.Task`1[[System.Boolean, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

 
```

**Comment by mariodivece** [comment]
What is the `Source` url you are using?

**Comment by olegsavelos** [comment]
Hmm it was some Youtube video streams, the crashes occurred either when seeking the video or just playing.

**Comment by mariodivece** [comment]
build from zeranoe or custom build of ffmpeg?

**Comment by mariodivece** [comment]
does it do the same with the sample app?

**Comment by mariodivece** [comment]
There was no additional feedback or similar reports. Closing. Feel free to open a new issue if you have proper steps and media to reproduce the issue.

**Comment by olegsavelos** [comment]
Hey, sorry did not have time. Will re open once i have time to replicate it.
