### ISSUE TITLE
App shuts down with two or more FFME surrounded by ViewBox control and multi threaded video set to true.

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#396]
# Issue Title (*App shuts down with two or more FFME surrounded by the same ViewBox control and multi threaded video set to true. *)

When you have Unosquare.FFME.Library.EnableWpfMultiThreadedVideo = true set for 2 or more FFME video players that are both surrounded by the same ViewBox control, then load videos into both players the app shuts down with the exception below.
Despite the exception referencing closed captions, no settings are adjusted for closed captions at all so they would be at the control default.

The problem only occurs when you have more than 1 player. A single player on its own does not cause problems.

System.InvalidOperationException
  HResult=0x80131509
  Message=Layout measurement override of element 'Unosquare.FFME.Rendering.ClosedCaptionsControl' should not return PositiveInfinity as its DesiredSize, even if Infinity is passed in as available size.
  Source=PresentationCore
  StackTrace:
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at DVPlay.App.Main()

## Issue Categories
 - [X] Not sure

## Version Information

 - [4.1.3 ] NuGet Package *Enter Version Number Here*

## Steps to Reproduce

 1. Place a grid on a WPF window.
 2. Surround this grid with a ViewBox control
 3. Create two or more child grids and make the children of the first grid 
 4. Add a FFME player control to each child grid.
 5.  Set Unosquare.FFME.Library.EnableWpfMultiThreadedVideo = true for both players
 6. Load a video into each FFME player 

## Expected Results

 - App should shut down with the listed exception

**Comment by mariodivece** [comment]
I reproduced your issue. WPF multithreaded video is an unsupported feature but I will look into this.
