### ISSUE TITLE
System.TimeoutException: Failed to acquire lock on MME interop call on a timely manner error

### ISSUE THREAD

**Issue by manity42** [unosquare/ffmediaelement#402]
# Issue Title (System.TimeoutException: 'Failed to acquire lock on MME interop call on a timely manner.')

I am loading 4 videos in 4 players at one time. the videos are MP4.
Every once in a while on load of the 4 videos vs2017 goes into break mode with this message.
This is very intermittent. sometimes it can happen 5 times in a row. Sometimes it does not happen at all.

message is:
An unhandled exception of type 'System.TimeoutException' occurred in ffme.win.dll
Failed to acquire lock on MME interop call on a timely manner.

Im not sure what i can or should do to try and isolate what is causing this.
I have the details below and the exception information seems to relate to the audio component.

i have tried using     FFMEMediaPlayer.RendererOptions.UseLegacyAudioOut = true; in the media opening event. But it neither improves nor makes worse the problem. Its still the same.

Are there any suggestions on how i could tackle this please.

System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DVPlayback.exe</AppDomain><Exception><ExceptionType>System.TimeoutException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Failed to acquire lock on MME interop call on a timely manner.</Message><StackTrace>   at Unosquare.FFME.Rendering.Wave.WaveInterop.TryEnterWaveOperation(IntPtr deviceHandle)
   at Unosquare.FFME.Rendering.Wave.WaveInterop.WriteAudioData(IntPtr deviceHandle, WaveHeader header)
   at Unosquare.FFME.Rendering.Wave.WaveOutBuffer.ReadWaveStream()
   at Unosquare.FFME.Rendering.Wave.LegacyAudioPlayer.PerformContinuousPlayback()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>System.TimeoutException: Failed to acquire lock on MME interop call on a timely manner.
   at Unosquare.FFME.Rendering.Wave.WaveInterop.TryEnterWaveOperation(IntPtr deviceHandle)
   at Unosquare.FFME.Rendering.Wave.WaveInterop.WriteAudioData(IntPtr deviceHandle, WaveHeader header)
   at Unosquare.FFME.Rendering.Wave.WaveOutBuffer.ReadWaveStream()
   at Unosquare.FFME.Rendering.Wave.LegacyAudioPlayer.PerformContinuousPlayback()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.TimeoutException' occurred in ffme.win.dll
Failed to acquire lock on MME interop call on a timely manner.

 - [ X] Not sure

## Version Information

 - [4.13 ] NuGet Package *Enter Version Number Here*

**Comment by mariodivece** [comment]
MME (multimedia extensions Win32 API) is in fact the legacy audio API. Try with DirectSound instead. `UseLegacyAudioOut = false`

It is still weird though... MME should work fine -- What are your system specs?

**Comment by manity42** [comment]
MSI-7978 i7-6700cpu GTX1050 Realtek High Definition onboard audio 16GB ram.

I should mention i swapped to using legacy mode because i was getting an occasionally exception like this, exception thrown at 0x269824E1 (dsound.dll). I thought it might be related to this issue
https://github.com/unosquare/ffmediaelement/issues/388
so i changed to using legacy audio mode. While this dsound.dll exception went away then the MME exception i listed above started intermittently occurring. 

I cant reproduce it consistently. it seems fairly random 

Im using Nuget package 4.13 that installs with FFMPEG.Autogen v4.1.0.2
But i notice there is an update to of FFMPEG.Autogen v4.1.04 
Should i try to update Autogen ? see if that makes a difference ?

**Comment by manity42** [comment]
I am closing this issue. So far since reconstituting my project in version 4.1310 of the control this issue has not occurred. I have no idea what was causing it and it was completely random, i could not force it occur on demand. If it occurs again i will re-open this issue.
