### ISSUE TITLE
System.ArgumentException: URI formats are not supported.

### ISSUE THREAD

**Issue by RMAKevin** [unosquare/ffmediaelement#403]
# System.ArgumentException: URI formats are not supported.

I am just starting to use this library, so this may be a really easy question, but I'm confused.
When I try to set the source the MediaFailed event is thrown with this:
System.ArgumentException: URI formats are not supported.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at FFmpeg.AutoGen.FFInterop.Initialize(String overridePath, Int32 libIdentifiers)
   at Unosquare.FFME.Library.LoadFFmpeg()
   at Unosquare.FFME.Commands.CommandManager.CommandOpenMedia(IMediaInputStream inputStream, Uri streamUri)
   at Unosquare.FFME.Commands.CommandManager.<>c__DisplayClass47_0.<ExecuteDirectCommand>b__0()

URI is what Source requires, but is not supported?

## Issue Categories

 - [ ] Bug
 - [ ] Feature Request
 - [x] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.1.300*
 - [ ] Build From *Master* branch, Commit *Enter commit id. Example: 704c482*
 - [ ] Build from *Branch Name*, Commit *Enter commit id. Example: 704c482*

## Steps to Reproduce

 1. I did a Directory.GetFiles(dir) call to get some files
 2. then used new Uri(Directory.GetFiles(dir)[0])
 3. and passed the uri to the ffme.Source

Note: Im also creating the element via code (not in XAML) and adding it to a Canvas.
 
### C#
```csharp
            var files = Directory.GetFiles(fullDir);
            if (!ParentForm.Canvas.Children.Contains(_ffmeElement))
            {
                ParentForm.Canvas.Children.Add(_ffmeElement);
            }
            if (!_ffmeElement.IsPlaying)
            {
                _ffmeElement.ScrubbingEnabled = true;
                _ffmeElement.MediaFailed += _ffmeElement_MediaFailed;
                _ffmeElement.MediaOpened += FfmeElement_MediaOpened;
                _ffmeElement.MediaEnded += FfmeElement_MediaEnded;
                var uri = new Uri(files[fileIndex]);
                _ffmeElement.Source = uri;
                _ffmeElement.Play();
            }
```

Thanks in advance

**Comment by RMAKevin** [comment]
As for the original problem; the "System.ArgumentException: URI formats are not supported." issue was caused when setting Unosquare.FFME.Library.FFmpegDirectory. That was my beginners mistake. It was confusing that the errors in setting the FFmpegDirectory only reports when trying to open media.

I also came across some problems when trying to reference the library through reflection. I could not use my Target Framework of 4.0 (i read somewhere that the Uri syntax changed) So that also caused some grief. But I got it working with 4.5, Just wanted to leave that here if someone else reads this.
