### ISSUE TITLE
System.ObjectDisposedException: The CancellationTokenSource has been disposed. while looping video

### ISSUE THREAD

**Issue by RMAKevin** [unosquare/ffmediaelement#406]
# System.ObjectDisposedException: The CancellationTokenSource has been disposed. while looping video

*I have a simple app running to test this player. I play 1 video on loop using the MediaEnded event. But after maybe an hour of running, it crashes with this error:*

System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.InternalRegisterWithoutEC(Action`1 callback, Object state)
   at System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationToken cancellationToken)
   at Unosquare.FFME.Primitives.ThreadWorkerBase.RunWorkerLoop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

## Issue Categories

 - [x] Bug
 - [ ] Feature Request
 - [ ] Question
 - [ ] Not sure

## Version Information

 - [x] NuGet Package *4.1.300*

## Steps to Reproduce

 1. I just let a video file play and loop when ended
 
### C#
```csharp
            if (!ParentForm.Canvas.Children.Contains(_ffmeElement))
            {
                _ffmeElement.Height = ParentForm.Canvas.ActualHeight;
                _ffmeElement.Width = ParentForm.Canvas.ActualWidth;
                ParentForm.Canvas.Children.Add(_ffmeElement);
            }
            _ffmeElement.LoadedBehavior = Unosquare.FFME.Common.MediaPlaybackState.Manual;
            if (!_ffmeElement.IsPlaying)
            {
                _ffmeElement.ScrubbingEnabled = true;
                _ffmeElement.MediaFailed += FfmeElement_MediaFailed;
                _ffmeElement.MediaOpened += FfmeElement_MediaOpened;
                _ffmeElement.MediaEnded += FfmeElement_MediaEnded;
                _ffmeElement.MessageLogged += _ffmeElement_MessageLogged;
                var uri = new Uri(files[fileIndex], UriKind.Absolute);
                _ffmeElement.Source = uri;
                _log.Error("FFMEPlayer.Play: Source=" + uri.ToString());
                _ffmeElement.Play();
            }

        private async void FfmeElement_MediaEnded(object sender, EventArgs e)
        {
            await _ffmeElement.Stop();
            await _ffmeElement.Play();
        }
```
The Error came from either the FrameDecodingWorker or BlockRenderingWorker thread. its crashed a couple of times.
Please help.

**Comment by mariodivece** [comment]
yep you're right. After carefully reading the following post, I realized that calling dispose for the purposes of the functionality of FFME is not necessary.

https://stackoverflow.com/questions/6960520/when-to-dispose-cancellationtokensource
